"""empty message

Revision ID: 979ca77f4124
Revises: 
Create Date: 2021-05-22 20:21:55.539038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979ca77f4124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
